easy_admin:
    entities:
#        # List the entity class name you want to manage
         - App\Entity\Personne
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
